name: SRMS GitHub Actions CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Restore Packages
        working-directory: .
        run: dotnet restore ./StudentResultApp.sln

      - name: Build Application
        working-directory: .
        run: dotnet build ./StudentResultApp.sln --configuration Release --no-restore

      - name: Run Tests
        working-directory: .
        run: dotnet test ./StudentResultApp.sln --configuration Release --no-build --filter "FullyQualifiedName!~StudentResultUiTests"

      - name: Publish Application
        working-directory: .
        run: dotnet publish ./StudentResultApp/StudentResultApp.csproj --configuration Release --output ./publish

      - name: Deploy Stage
        run: echo "Deployment completed successfully"